apiVersion: v1
kind: Service

metadata:
  name: devops-learning-service
  namespace: {{ .Values.namespace }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app: devops-learning-app

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}