apiVersion: v1
kind: Service
metadata:
  name: devops-learning-service
spec:
  type: NodePort
  selector:
    app: devops-learning-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30090