apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

commonAnnotations:
  buildTime: "test-001"

images:
  - name: prabhran/my-demo-app
    newTag: latest