name: Test

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:

     -name: checkout code
      uses: actions/checkout@v4

      -name: build docker image
       run: docker build -t my-demo-app -f docker/Dockerfile .
